apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-voting
      tier: database
      dbtype: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: e-voting
        tier: database
        dbtype: postgres
    spec:
      containers:
        - name: postgres
          image: postgre
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"