apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-voting
      tier: front-end
      appType: voting
  template:
    metadata:
      name: voting-app
      labels:
        app: e-voting
        tier: front-end
        appType: voting
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80