apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-voting
      tier: back-end
  template:
    metadata:
      name: worker
      labels:
        app: e-voting
        tier: back-end
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1