apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: e-voting
    tier: database-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: e-voting
    dbtype: postgres