apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: e-voting
    tier: database-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: e-voting
    dbtype: redis