apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    app: e-voting
    tier: front-end-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: e-voting
    appType: result