apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    app: e-voting
    tier: front-end-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: e-voting
    appType: voting