apiVersion: v1
kind: Pod
metadata:
  name: result-app
  labels:
    app: e-voting
    tier: front-end
    appType: result
spec:
  containers:
    - name: result-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80